// Generated by dts-bundle-generator v9.5.1

export declare class Parser {
	static parse(input: string): number;
	private static _getTokens;
	private static _isAdditionToken;
	private static _isMultiplicationToken;
	private static _isExponentiationToken;
	private readonly _tokens;
	private _index;
	private constructor();
	private get _current();
	parse(): number;
	private _peekAhead;
	private _next;
	private _parseExpression;
	private _parseTerm;
	private _parseFactor;
	private _parseExponent;
	private _parseFactorial;
	private _handleGroup;
	private _handleNumber;
	private _advance;
	private _assertToken;
	private _throw;
}

export {};
